<?php
/**
 * MarketCalendarDay
 *
 * PHP version 8.1
 *
 * @package  Repull
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Repull API
 *
 * The unified API for vacation rental tech. Connect to 50+ PMS platforms and 4 OTA channels through one REST API. Built-in AI operations for guest communication, pricing, and listing optimization.  ## Quick Start 1. Get an API key at https://repull.dev/dashboard 2. Connect a PMS: `POST /v1/connect/{provider}` 3. List properties: `GET /v1/properties` 4. Get reservations: `GET /v1/reservations`  ## Authentication All requests require a Bearer token: ``` Authorization: Bearer sk_test_YOUR_API_KEY ```  Sandbox keys start with `sk_test_`, production with `sk_live_`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ivan@vanio.ai
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Repull\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Repull\ObjectSerializer;

/**
 * MarketCalendarDay Class Doc Comment
 *
 * @package  Repull
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class MarketCalendarDay implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'MarketCalendarDay';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'date' => '\DateTime',
        'market_avg_rate' => 'float',
        'market_min_rate' => 'float',
        'market_max_rate' => 'float',
        'priced_listings' => 'int',
        'occupancy_pct' => 'float',
        'total_listings' => 'int',
        'wheelhouse_occupancy' => 'float',
        'wheelhouse_adr' => 'float',
        'events' => '\Repull\Model\MarketCalendarDayEventsInner[]',
        'my_price' => 'float',
        'my_available' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'date' => 'date',
        'market_avg_rate' => null,
        'market_min_rate' => null,
        'market_max_rate' => null,
        'priced_listings' => null,
        'occupancy_pct' => null,
        'total_listings' => null,
        'wheelhouse_occupancy' => null,
        'wheelhouse_adr' => null,
        'events' => null,
        'my_price' => null,
        'my_available' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'date' => false,
        'market_avg_rate' => true,
        'market_min_rate' => true,
        'market_max_rate' => true,
        'priced_listings' => false,
        'occupancy_pct' => true,
        'total_listings' => false,
        'wheelhouse_occupancy' => true,
        'wheelhouse_adr' => true,
        'events' => false,
        'my_price' => true,
        'my_available' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'date' => 'date',
        'market_avg_rate' => 'marketAvgRate',
        'market_min_rate' => 'marketMinRate',
        'market_max_rate' => 'marketMaxRate',
        'priced_listings' => 'pricedListings',
        'occupancy_pct' => 'occupancyPct',
        'total_listings' => 'totalListings',
        'wheelhouse_occupancy' => 'wheelhouseOccupancy',
        'wheelhouse_adr' => 'wheelhouseAdr',
        'events' => 'events',
        'my_price' => 'myPrice',
        'my_available' => 'myAvailable'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'date' => 'setDate',
        'market_avg_rate' => 'setMarketAvgRate',
        'market_min_rate' => 'setMarketMinRate',
        'market_max_rate' => 'setMarketMaxRate',
        'priced_listings' => 'setPricedListings',
        'occupancy_pct' => 'setOccupancyPct',
        'total_listings' => 'setTotalListings',
        'wheelhouse_occupancy' => 'setWheelhouseOccupancy',
        'wheelhouse_adr' => 'setWheelhouseAdr',
        'events' => 'setEvents',
        'my_price' => 'setMyPrice',
        'my_available' => 'setMyAvailable'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'date' => 'getDate',
        'market_avg_rate' => 'getMarketAvgRate',
        'market_min_rate' => 'getMarketMinRate',
        'market_max_rate' => 'getMarketMaxRate',
        'priced_listings' => 'getPricedListings',
        'occupancy_pct' => 'getOccupancyPct',
        'total_listings' => 'getTotalListings',
        'wheelhouse_occupancy' => 'getWheelhouseOccupancy',
        'wheelhouse_adr' => 'getWheelhouseAdr',
        'events' => 'getEvents',
        'my_price' => 'getMyPrice',
        'my_available' => 'getMyAvailable'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('date', $data ?? [], null);
        $this->setIfExists('market_avg_rate', $data ?? [], null);
        $this->setIfExists('market_min_rate', $data ?? [], null);
        $this->setIfExists('market_max_rate', $data ?? [], null);
        $this->setIfExists('priced_listings', $data ?? [], null);
        $this->setIfExists('occupancy_pct', $data ?? [], null);
        $this->setIfExists('total_listings', $data ?? [], null);
        $this->setIfExists('wheelhouse_occupancy', $data ?? [], null);
        $this->setIfExists('wheelhouse_adr', $data ?? [], null);
        $this->setIfExists('events', $data ?? [], null);
        $this->setIfExists('my_price', $data ?? [], null);
        $this->setIfExists('my_available', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets date
     *
     * @return \DateTime|null
     */
    public function getDate(): ?\DateTime
    {
        return $this->container['date'];
    }

    /**
     * Sets date
     *
     * @param \DateTime|null $date date
     *
     * @return $this
     */
    public function setDate(?\DateTime $date): static
    {
        if (is_null($date)) {
            throw new InvalidArgumentException('non-nullable date cannot be null');
        }
        $this->container['date'] = $date;

        return $this;
    }

    /**
     * Gets market_avg_rate
     *
     * @return float|null
     */
    public function getMarketAvgRate(): ?float
    {
        return $this->container['market_avg_rate'];
    }

    /**
     * Sets market_avg_rate
     *
     * @param float|null $market_avg_rate market_avg_rate
     *
     * @return $this
     */
    public function setMarketAvgRate(?float $market_avg_rate): static
    {
        if (is_null($market_avg_rate)) {
            array_push($this->openAPINullablesSetToNull, 'market_avg_rate');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('market_avg_rate', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['market_avg_rate'] = $market_avg_rate;

        return $this;
    }

    /**
     * Gets market_min_rate
     *
     * @return float|null
     */
    public function getMarketMinRate(): ?float
    {
        return $this->container['market_min_rate'];
    }

    /**
     * Sets market_min_rate
     *
     * @param float|null $market_min_rate market_min_rate
     *
     * @return $this
     */
    public function setMarketMinRate(?float $market_min_rate): static
    {
        if (is_null($market_min_rate)) {
            array_push($this->openAPINullablesSetToNull, 'market_min_rate');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('market_min_rate', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['market_min_rate'] = $market_min_rate;

        return $this;
    }

    /**
     * Gets market_max_rate
     *
     * @return float|null
     */
    public function getMarketMaxRate(): ?float
    {
        return $this->container['market_max_rate'];
    }

    /**
     * Sets market_max_rate
     *
     * @param float|null $market_max_rate market_max_rate
     *
     * @return $this
     */
    public function setMarketMaxRate(?float $market_max_rate): static
    {
        if (is_null($market_max_rate)) {
            array_push($this->openAPINullablesSetToNull, 'market_max_rate');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('market_max_rate', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['market_max_rate'] = $market_max_rate;

        return $this;
    }

    /**
     * Gets priced_listings
     *
     * @return int|null
     */
    public function getPricedListings(): ?int
    {
        return $this->container['priced_listings'];
    }

    /**
     * Sets priced_listings
     *
     * @param int|null $priced_listings priced_listings
     *
     * @return $this
     */
    public function setPricedListings(?int $priced_listings): static
    {
        if (is_null($priced_listings)) {
            throw new InvalidArgumentException('non-nullable priced_listings cannot be null');
        }
        $this->container['priced_listings'] = $priced_listings;

        return $this;
    }

    /**
     * Gets occupancy_pct
     *
     * @return float|null
     */
    public function getOccupancyPct(): ?float
    {
        return $this->container['occupancy_pct'];
    }

    /**
     * Sets occupancy_pct
     *
     * @param float|null $occupancy_pct occupancy_pct
     *
     * @return $this
     */
    public function setOccupancyPct(?float $occupancy_pct): static
    {
        if (is_null($occupancy_pct)) {
            array_push($this->openAPINullablesSetToNull, 'occupancy_pct');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('occupancy_pct', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['occupancy_pct'] = $occupancy_pct;

        return $this;
    }

    /**
     * Gets total_listings
     *
     * @return int|null
     */
    public function getTotalListings(): ?int
    {
        return $this->container['total_listings'];
    }

    /**
     * Sets total_listings
     *
     * @param int|null $total_listings total_listings
     *
     * @return $this
     */
    public function setTotalListings(?int $total_listings): static
    {
        if (is_null($total_listings)) {
            throw new InvalidArgumentException('non-nullable total_listings cannot be null');
        }
        $this->container['total_listings'] = $total_listings;

        return $this;
    }

    /**
     * Gets wheelhouse_occupancy
     *
     * @return float|null
     */
    public function getWheelhouseOccupancy(): ?float
    {
        return $this->container['wheelhouse_occupancy'];
    }

    /**
     * Sets wheelhouse_occupancy
     *
     * @param float|null $wheelhouse_occupancy wheelhouse_occupancy
     *
     * @return $this
     */
    public function setWheelhouseOccupancy(?float $wheelhouse_occupancy): static
    {
        if (is_null($wheelhouse_occupancy)) {
            array_push($this->openAPINullablesSetToNull, 'wheelhouse_occupancy');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('wheelhouse_occupancy', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['wheelhouse_occupancy'] = $wheelhouse_occupancy;

        return $this;
    }

    /**
     * Gets wheelhouse_adr
     *
     * @return float|null
     */
    public function getWheelhouseAdr(): ?float
    {
        return $this->container['wheelhouse_adr'];
    }

    /**
     * Sets wheelhouse_adr
     *
     * @param float|null $wheelhouse_adr wheelhouse_adr
     *
     * @return $this
     */
    public function setWheelhouseAdr(?float $wheelhouse_adr): static
    {
        if (is_null($wheelhouse_adr)) {
            array_push($this->openAPINullablesSetToNull, 'wheelhouse_adr');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('wheelhouse_adr', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['wheelhouse_adr'] = $wheelhouse_adr;

        return $this;
    }

    /**
     * Gets events
     *
     * @return \Repull\Model\MarketCalendarDayEventsInner[]|null
     */
    public function getEvents(): ?array
    {
        return $this->container['events'];
    }

    /**
     * Sets events
     *
     * @param \Repull\Model\MarketCalendarDayEventsInner[]|null $events events
     *
     * @return $this
     */
    public function setEvents(?array $events): static
    {
        if (is_null($events)) {
            throw new InvalidArgumentException('non-nullable events cannot be null');
        }
        $this->container['events'] = $events;

        return $this;
    }

    /**
     * Gets my_price
     *
     * @return float|null
     */
    public function getMyPrice(): ?float
    {
        return $this->container['my_price'];
    }

    /**
     * Sets my_price
     *
     * @param float|null $my_price Only present when `listingId` is supplied.
     *
     * @return $this
     */
    public function setMyPrice(?float $my_price): static
    {
        if (is_null($my_price)) {
            array_push($this->openAPINullablesSetToNull, 'my_price');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('my_price', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['my_price'] = $my_price;

        return $this;
    }

    /**
     * Gets my_available
     *
     * @return bool|null
     */
    public function getMyAvailable(): ?bool
    {
        return $this->container['my_available'];
    }

    /**
     * Sets my_available
     *
     * @param bool|null $my_available Only meaningful when `listingId` is supplied.
     *
     * @return $this
     */
    public function setMyAvailable(?bool $my_available): static
    {
        if (is_null($my_available)) {
            throw new InvalidArgumentException('non-nullable my_available cannot be null');
        }
        $this->container['my_available'] = $my_available;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


