<?php
/**
 * BookingComApi
 * PHP version 8.1
 *
 * @package  Repull
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Repull API
 *
 * The unified API for vacation rental tech. Connect to 50+ PMS platforms and 4 OTA channels through one REST API. Built-in AI operations for guest communication, pricing, and listing optimization.  ## Quick Start 1. Get an API key at https://repull.dev/dashboard 2. Connect a PMS: `POST /v1/connect/{provider}` 3. List properties: `GET /v1/properties` 4. Get reservations: `GET /v1/reservations`  ## Authentication All requests require a Bearer token: ``` Authorization: Bearer sk_test_YOUR_API_KEY ```  Sandbox keys start with `sk_test_`, production with `sk_live_`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ivan@vanio.ai
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Repull\Api;

use InvalidArgumentException;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use GuzzleHttp\Promise\PromiseInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Repull\ApiException;
use Repull\Configuration;
use Repull\HeaderSelector;
use Repull\FormDataProcessor;
use Repull\ObjectSerializer;

/**
 * BookingComApi Class Doc Comment
 *
 * @package  Repull
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BookingComApi
{
    /**
     * @var ClientInterface
     */
    protected ClientInterface $client;

    /**
     * @var Configuration
     */
    protected Configuration $config;

    /**
     * @var HeaderSelector
     */
    protected HeaderSelector $headerSelector;

    /**
     * @var int Host index
     */
    protected int $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'v1ChannelsBookingAvailabilityPut' => [
            'application/json',
        ],
        'v1ChannelsBookingContentGet' => [
            'application/json',
        ],
        'v1ChannelsBookingContentPost' => [
            'application/json',
        ],
        'v1ChannelsBookingMessagingGet' => [
            'application/json',
        ],
        'v1ChannelsBookingMessagingPost' => [
            'application/json',
        ],
        'v1ChannelsBookingPropertiesGet' => [
            'application/json',
        ],
        'v1ChannelsBookingPropertiesPost' => [
            'application/json',
        ],
        'v1ChannelsBookingSyncPost' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null   $config
     * @param HeaderSelector|null  $selector
     * @param int                  $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Operation v1ChannelsBookingAvailabilityPut
     *
     * Update Booking.com rates/availability
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingAvailabilityPut'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return void
     */
    public function v1ChannelsBookingAvailabilityPut(
        string $contentType = self::contentTypes['v1ChannelsBookingAvailabilityPut'][0]
    ): void
    {
        $this->v1ChannelsBookingAvailabilityPutWithHttpInfo($contentType);
    }

    /**
     * Operation v1ChannelsBookingAvailabilityPutWithHttpInfo
     *
     * Update Booking.com rates/availability
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingAvailabilityPut'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1ChannelsBookingAvailabilityPutWithHttpInfo(
        string $contentType = self::contentTypes['v1ChannelsBookingAvailabilityPut'][0]
    ): array
    {
        $request = $this->v1ChannelsBookingAvailabilityPutRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        
            throw $e;
        }
    }

    /**
     * Operation v1ChannelsBookingAvailabilityPutAsync
     *
     * Update Booking.com rates/availability
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingAvailabilityPut'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function v1ChannelsBookingAvailabilityPutAsync(
        string $contentType = self::contentTypes['v1ChannelsBookingAvailabilityPut'][0]
    ): PromiseInterface
    {
        return $this->v1ChannelsBookingAvailabilityPutAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1ChannelsBookingAvailabilityPutAsyncWithHttpInfo
     *
     * Update Booking.com rates/availability
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingAvailabilityPut'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function v1ChannelsBookingAvailabilityPutAsyncWithHttpInfo(
        string $contentType = self::contentTypes['v1ChannelsBookingAvailabilityPut'][0]
    ): PromiseInterface
    {
        $returnType = '';
        $request = $this->v1ChannelsBookingAvailabilityPutRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1ChannelsBookingAvailabilityPut'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingAvailabilityPut'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1ChannelsBookingAvailabilityPutRequest(
        string $contentType = self::contentTypes['v1ChannelsBookingAvailabilityPut'][0]
    ): Request
    {


        $resourcePath = '/v1/channels/booking/availability';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (API Key) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1ChannelsBookingContentGet
     *
     * Get Booking.com content
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingContentGet'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return void
     */
    public function v1ChannelsBookingContentGet(
        string $contentType = self::contentTypes['v1ChannelsBookingContentGet'][0]
    ): void
    {
        $this->v1ChannelsBookingContentGetWithHttpInfo($contentType);
    }

    /**
     * Operation v1ChannelsBookingContentGetWithHttpInfo
     *
     * Get Booking.com content
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingContentGet'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1ChannelsBookingContentGetWithHttpInfo(
        string $contentType = self::contentTypes['v1ChannelsBookingContentGet'][0]
    ): array
    {
        $request = $this->v1ChannelsBookingContentGetRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        
            throw $e;
        }
    }

    /**
     * Operation v1ChannelsBookingContentGetAsync
     *
     * Get Booking.com content
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingContentGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function v1ChannelsBookingContentGetAsync(
        string $contentType = self::contentTypes['v1ChannelsBookingContentGet'][0]
    ): PromiseInterface
    {
        return $this->v1ChannelsBookingContentGetAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1ChannelsBookingContentGetAsyncWithHttpInfo
     *
     * Get Booking.com content
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingContentGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function v1ChannelsBookingContentGetAsyncWithHttpInfo(
        string $contentType = self::contentTypes['v1ChannelsBookingContentGet'][0]
    ): PromiseInterface
    {
        $returnType = '';
        $request = $this->v1ChannelsBookingContentGetRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1ChannelsBookingContentGet'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingContentGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1ChannelsBookingContentGetRequest(
        string $contentType = self::contentTypes['v1ChannelsBookingContentGet'][0]
    ): Request
    {


        $resourcePath = '/v1/channels/booking/content';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (API Key) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1ChannelsBookingContentPost
     *
     * Update Booking.com content
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingContentPost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return void
     */
    public function v1ChannelsBookingContentPost(
        string $contentType = self::contentTypes['v1ChannelsBookingContentPost'][0]
    ): void
    {
        $this->v1ChannelsBookingContentPostWithHttpInfo($contentType);
    }

    /**
     * Operation v1ChannelsBookingContentPostWithHttpInfo
     *
     * Update Booking.com content
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingContentPost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1ChannelsBookingContentPostWithHttpInfo(
        string $contentType = self::contentTypes['v1ChannelsBookingContentPost'][0]
    ): array
    {
        $request = $this->v1ChannelsBookingContentPostRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        
            throw $e;
        }
    }

    /**
     * Operation v1ChannelsBookingContentPostAsync
     *
     * Update Booking.com content
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingContentPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function v1ChannelsBookingContentPostAsync(
        string $contentType = self::contentTypes['v1ChannelsBookingContentPost'][0]
    ): PromiseInterface
    {
        return $this->v1ChannelsBookingContentPostAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1ChannelsBookingContentPostAsyncWithHttpInfo
     *
     * Update Booking.com content
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingContentPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function v1ChannelsBookingContentPostAsyncWithHttpInfo(
        string $contentType = self::contentTypes['v1ChannelsBookingContentPost'][0]
    ): PromiseInterface
    {
        $returnType = '';
        $request = $this->v1ChannelsBookingContentPostRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1ChannelsBookingContentPost'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingContentPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1ChannelsBookingContentPostRequest(
        string $contentType = self::contentTypes['v1ChannelsBookingContentPost'][0]
    ): Request
    {


        $resourcePath = '/v1/channels/booking/content';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (API Key) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1ChannelsBookingMessagingGet
     *
     * List Booking.com conversations
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingMessagingGet'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return void
     */
    public function v1ChannelsBookingMessagingGet(
        string $contentType = self::contentTypes['v1ChannelsBookingMessagingGet'][0]
    ): void
    {
        $this->v1ChannelsBookingMessagingGetWithHttpInfo($contentType);
    }

    /**
     * Operation v1ChannelsBookingMessagingGetWithHttpInfo
     *
     * List Booking.com conversations
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingMessagingGet'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1ChannelsBookingMessagingGetWithHttpInfo(
        string $contentType = self::contentTypes['v1ChannelsBookingMessagingGet'][0]
    ): array
    {
        $request = $this->v1ChannelsBookingMessagingGetRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        
            throw $e;
        }
    }

    /**
     * Operation v1ChannelsBookingMessagingGetAsync
     *
     * List Booking.com conversations
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingMessagingGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function v1ChannelsBookingMessagingGetAsync(
        string $contentType = self::contentTypes['v1ChannelsBookingMessagingGet'][0]
    ): PromiseInterface
    {
        return $this->v1ChannelsBookingMessagingGetAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1ChannelsBookingMessagingGetAsyncWithHttpInfo
     *
     * List Booking.com conversations
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingMessagingGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function v1ChannelsBookingMessagingGetAsyncWithHttpInfo(
        string $contentType = self::contentTypes['v1ChannelsBookingMessagingGet'][0]
    ): PromiseInterface
    {
        $returnType = '';
        $request = $this->v1ChannelsBookingMessagingGetRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1ChannelsBookingMessagingGet'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingMessagingGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1ChannelsBookingMessagingGetRequest(
        string $contentType = self::contentTypes['v1ChannelsBookingMessagingGet'][0]
    ): Request
    {


        $resourcePath = '/v1/channels/booking/messaging';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (API Key) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1ChannelsBookingMessagingPost
     *
     * Send Booking.com message
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingMessagingPost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return void
     */
    public function v1ChannelsBookingMessagingPost(
        string $contentType = self::contentTypes['v1ChannelsBookingMessagingPost'][0]
    ): void
    {
        $this->v1ChannelsBookingMessagingPostWithHttpInfo($contentType);
    }

    /**
     * Operation v1ChannelsBookingMessagingPostWithHttpInfo
     *
     * Send Booking.com message
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingMessagingPost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1ChannelsBookingMessagingPostWithHttpInfo(
        string $contentType = self::contentTypes['v1ChannelsBookingMessagingPost'][0]
    ): array
    {
        $request = $this->v1ChannelsBookingMessagingPostRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        
            throw $e;
        }
    }

    /**
     * Operation v1ChannelsBookingMessagingPostAsync
     *
     * Send Booking.com message
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingMessagingPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function v1ChannelsBookingMessagingPostAsync(
        string $contentType = self::contentTypes['v1ChannelsBookingMessagingPost'][0]
    ): PromiseInterface
    {
        return $this->v1ChannelsBookingMessagingPostAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1ChannelsBookingMessagingPostAsyncWithHttpInfo
     *
     * Send Booking.com message
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingMessagingPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function v1ChannelsBookingMessagingPostAsyncWithHttpInfo(
        string $contentType = self::contentTypes['v1ChannelsBookingMessagingPost'][0]
    ): PromiseInterface
    {
        $returnType = '';
        $request = $this->v1ChannelsBookingMessagingPostRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1ChannelsBookingMessagingPost'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingMessagingPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1ChannelsBookingMessagingPostRequest(
        string $contentType = self::contentTypes['v1ChannelsBookingMessagingPost'][0]
    ): Request
    {


        $resourcePath = '/v1/channels/booking/messaging';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (API Key) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1ChannelsBookingPropertiesGet
     *
     * List Booking.com properties
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingPropertiesGet'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return void
     */
    public function v1ChannelsBookingPropertiesGet(
        string $contentType = self::contentTypes['v1ChannelsBookingPropertiesGet'][0]
    ): void
    {
        $this->v1ChannelsBookingPropertiesGetWithHttpInfo($contentType);
    }

    /**
     * Operation v1ChannelsBookingPropertiesGetWithHttpInfo
     *
     * List Booking.com properties
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingPropertiesGet'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1ChannelsBookingPropertiesGetWithHttpInfo(
        string $contentType = self::contentTypes['v1ChannelsBookingPropertiesGet'][0]
    ): array
    {
        $request = $this->v1ChannelsBookingPropertiesGetRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        
            throw $e;
        }
    }

    /**
     * Operation v1ChannelsBookingPropertiesGetAsync
     *
     * List Booking.com properties
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingPropertiesGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function v1ChannelsBookingPropertiesGetAsync(
        string $contentType = self::contentTypes['v1ChannelsBookingPropertiesGet'][0]
    ): PromiseInterface
    {
        return $this->v1ChannelsBookingPropertiesGetAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1ChannelsBookingPropertiesGetAsyncWithHttpInfo
     *
     * List Booking.com properties
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingPropertiesGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function v1ChannelsBookingPropertiesGetAsyncWithHttpInfo(
        string $contentType = self::contentTypes['v1ChannelsBookingPropertiesGet'][0]
    ): PromiseInterface
    {
        $returnType = '';
        $request = $this->v1ChannelsBookingPropertiesGetRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1ChannelsBookingPropertiesGet'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingPropertiesGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1ChannelsBookingPropertiesGetRequest(
        string $contentType = self::contentTypes['v1ChannelsBookingPropertiesGet'][0]
    ): Request
    {


        $resourcePath = '/v1/channels/booking/properties';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (API Key) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1ChannelsBookingPropertiesPost
     *
     * Create Booking.com property
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingPropertiesPost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return void
     */
    public function v1ChannelsBookingPropertiesPost(
        string $contentType = self::contentTypes['v1ChannelsBookingPropertiesPost'][0]
    ): void
    {
        $this->v1ChannelsBookingPropertiesPostWithHttpInfo($contentType);
    }

    /**
     * Operation v1ChannelsBookingPropertiesPostWithHttpInfo
     *
     * Create Booking.com property
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingPropertiesPost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1ChannelsBookingPropertiesPostWithHttpInfo(
        string $contentType = self::contentTypes['v1ChannelsBookingPropertiesPost'][0]
    ): array
    {
        $request = $this->v1ChannelsBookingPropertiesPostRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        
            throw $e;
        }
    }

    /**
     * Operation v1ChannelsBookingPropertiesPostAsync
     *
     * Create Booking.com property
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingPropertiesPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function v1ChannelsBookingPropertiesPostAsync(
        string $contentType = self::contentTypes['v1ChannelsBookingPropertiesPost'][0]
    ): PromiseInterface
    {
        return $this->v1ChannelsBookingPropertiesPostAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1ChannelsBookingPropertiesPostAsyncWithHttpInfo
     *
     * Create Booking.com property
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingPropertiesPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function v1ChannelsBookingPropertiesPostAsyncWithHttpInfo(
        string $contentType = self::contentTypes['v1ChannelsBookingPropertiesPost'][0]
    ): PromiseInterface
    {
        $returnType = '';
        $request = $this->v1ChannelsBookingPropertiesPostRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1ChannelsBookingPropertiesPost'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingPropertiesPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1ChannelsBookingPropertiesPostRequest(
        string $contentType = self::contentTypes['v1ChannelsBookingPropertiesPost'][0]
    ): Request
    {


        $resourcePath = '/v1/channels/booking/properties';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (API Key) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1ChannelsBookingSyncPost
     *
     * Bulk sync to Booking.com
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingSyncPost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return void
     */
    public function v1ChannelsBookingSyncPost(
        string $contentType = self::contentTypes['v1ChannelsBookingSyncPost'][0]
    ): void
    {
        $this->v1ChannelsBookingSyncPostWithHttpInfo($contentType);
    }

    /**
     * Operation v1ChannelsBookingSyncPostWithHttpInfo
     *
     * Bulk sync to Booking.com
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingSyncPost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1ChannelsBookingSyncPostWithHttpInfo(
        string $contentType = self::contentTypes['v1ChannelsBookingSyncPost'][0]
    ): array
    {
        $request = $this->v1ChannelsBookingSyncPostRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        
            throw $e;
        }
    }

    /**
     * Operation v1ChannelsBookingSyncPostAsync
     *
     * Bulk sync to Booking.com
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingSyncPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function v1ChannelsBookingSyncPostAsync(
        string $contentType = self::contentTypes['v1ChannelsBookingSyncPost'][0]
    ): PromiseInterface
    {
        return $this->v1ChannelsBookingSyncPostAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1ChannelsBookingSyncPostAsyncWithHttpInfo
     *
     * Bulk sync to Booking.com
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingSyncPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function v1ChannelsBookingSyncPostAsyncWithHttpInfo(
        string $contentType = self::contentTypes['v1ChannelsBookingSyncPost'][0]
    ): PromiseInterface
    {
        $returnType = '';
        $request = $this->v1ChannelsBookingSyncPostRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1ChannelsBookingSyncPost'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1ChannelsBookingSyncPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1ChannelsBookingSyncPostRequest(
        string $contentType = self::contentTypes['v1ChannelsBookingSyncPost'][0]
    ): Request
    {


        $resourcePath = '/v1/channels/booking/sync';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (API Key) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response,
    ): array {
        if (in_array($dataType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode,
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
